package com.juhnowski.parkovka;

import java.util.ArrayList;
import java.util.HashMap;

public class AutoModels {
    public static HashMap<String,ArrayList<String>> getModels() {
        HashMap<String,ArrayList<String>> auto = new HashMap<String,ArrayList<String>>();
		ArrayList<String> audi = new ArrayList<String>();
audi.add("Audi A8");
audi.add("Audi A6");
audi.add("Audi A5");
audi.add("Audi A4");
audi.add("Audi A3");
audi.add("Audi S5");
audi.add("Audi RS 6 универсал");
audi.add("Audi A4 универсал");
audi.add("Audi А5 Sportback лифтбэк");
audi.add("Audi A7 Sportback лифтбэк");
audi.add("Audi S5 лифтбэк");
audi.add("Audi А3 Sportback хэтчбек");
audi.add("Audi A6 allroad quattro универсал");
audi.add("Audi E-tron кроссовер");
audi.add("Audi Q8 кроссовер");
audi.add("Audi SQ8 кроссовер");
audi.add("Audi Q3 кроссовер");
audi.add("Audi Q3 Sportback кроссовер");
audi.add("Audi Q5 кроссовер");
audi.add("Audi SQ5 кроссовер");
audi.add("Audi Q7 кроссовер");
audi.add("Audi 100");
audi.add("Audi 80");
audi.add("Audi 90");
audi.add("Audi A1 Sportback");
audi.add("Audi A2");
audi.add("Audi A3");
audi.add("Audi A4");
audi.add("Audi A4 allroad");
audi.add("Audi A5");
audi.add("Audi A6");
audi.add("Audi A6 allroad quattro");
audi.add("Audi A7 Sportback");
audi.add("Audi A8");
audi.add("Audi Cabriolet");
audi.add("Audi Q2");
audi.add("Audi Q3");
audi.add("Audi Q5");
audi.add("Audi Q7");
audi.add("Audi R8");
audi.add("Audi R8 GT");
audi.add("Audi RS 3");
audi.add("Audi RS 4");
audi.add("Audi RS 5");
audi.add("Audi RS 6");
audi.add("Audi RS 7 Sportback");
audi.add("Audi RS Q3");
audi.add("Audi RS Q3 Sportback");
audi.add("Audi S3");
audi.add("Audi S4");
audi.add("Audi S5");
audi.add("Audi S6");
audi.add("Audi S7 Sportback");
audi.add("Audi S8");
audi.add("Audi SQ5");
audi.add("Audi SQ7");
audi.add("Audi TT");
audi.add("Audi TT RS");
audi.add("Audi TT RS");
audi.add("Audi TTS");
auto.put("Audi",audi);
System.out.println("Количество моделей Audi: "+audi.size());

ArrayList<String> bmw = new ArrayList<String>();
bmw.add("BMW M2 купе");
bmw.add("BMW 7 седан");
bmw.add("BMW 8 купе");
bmw.add("BMW 8 Gran Coupe седан");
bmw.add("BMW 3 седан");
bmw.add("BMW 5 седан");
bmw.add("BMW M8 купе");
bmw.add("BMW M8 седан");
bmw.add("BMW 4 купе");
bmw.add("BMW M5 седан");
bmw.add("BMW 1 хэтчбек");
bmw.add("BMW 6 Gran Turismo лифтбэк");
bmw.add("BMW X2 кроссовер");
bmw.add("BMW X1 кроссовер");
bmw.add("BMW X3 кроссовер");
bmw.add("BMW X4 внедорожник");
bmw.add("BMW X5 внедорожник");
bmw.add("BMW X6 кроссовер");
bmw.add("BMW X7 кроссовер");
bmw.add("BMW 8 кабриолет");
bmw.add("BMW M8 кабриолет");
bmw.add("BMW 4 кабриолет");
bmw.add("BMW 1");
bmw.add("BMW 2");
bmw.add("BMW 2 Active Tourer");
bmw.add("BMW 2 Gran Tourer");
bmw.add("BMW 3");
bmw.add("BMW 3 Gran Turismo");
bmw.add("BMW 340");
bmw.add("BMW 4");
bmw.add("BMW 4 Gran Coupe");
bmw.add("BMW 5");
bmw.add("BMW 5 Gran Turismo");
bmw.add("BMW 6");
bmw.add("BMW 6 Gran Turismo");
bmw.add("BMW 7");
bmw.add("BMW 8");
bmw.add("BMW i3");
bmw.add("BMW i8");
bmw.add("BMW M Coupe");
bmw.add("BMW M135i");
bmw.add("BMW M2");
bmw.add("BMW M3");
bmw.add("BMW M4");
bmw.add("BMW M5");
bmw.add("BMW M6");
bmw.add("BMW M6 Gran Coupe");
bmw.add("BMW X1");
bmw.add("BMW X3");
bmw.add("BMW X3 M");
bmw.add("BMW X4");
bmw.add("BMW X4 M");
bmw.add("BMW X5");
bmw.add("BMW X5 M");
bmw.add("BMW X6");
bmw.add("BMW X6 M");
bmw.add("BMW Z1");
bmw.add("BMW Z3");
bmw.add("BMW Z4");
bmw.add("BMW Z4 M");
bmw.add("BMW Z8");
auto.put("BMW",bmw);
System.out.println("Количество моделей BMW: "+bmw.size());

ArrayList<String> ford = new ArrayList<String>();
ford.add("Ford Aerostar");
ford.add("Ford Aspire");
ford.add("Ford Bronco");
ford.add("Ford C-Max");
ford.add("Ford Contour");
ford.add("Ford Cougar");
ford.add("Ford Crown Victoria");
ford.add("Ford Econoline");
ford.add("Ford EcoSport");
ford.add("Ford Edge");
ford.add("Ford Escape");
ford.add("Ford Escort");
ford.add("Ford Excursion");
ford.add("Ford Expedition");
ford.add("Ford Explorer");
ford.add("Ford F-150");
ford.add("Ford F-350");
ford.add("Ford Fiesta");
ford.add("Ford Five Hundred");
ford.add("Ford Focus");
ford.add("Ford Focus RS");
ford.add("Ford Focus ST");
ford.add("Ford Freestyle");
ford.add("Ford Fusion");
ford.add("Ford Galaxy");
ford.add("Ford Grand C-Max");
ford.add("Ford GT");
ford.add("Ford Ka");
ford.add("Ford Kuga");
ford.add("Ford Maverick");
ford.add("Ford Mondeo");
ford.add("Ford Mustang");
ford.add("Ford Probe");
ford.add("Ford Puma");
ford.add("Ford Ranger");
ford.add("Ford S-Max");
ford.add("Ford Scorpio");
ford.add("Ford Sport KA");
ford.add("Ford Street KA");
ford.add("Ford Taurus");
ford.add("Ford Tempo");
ford.add("Ford Thunderbird");
ford.add("Ford Tourneo Connect");
ford.add("Ford Tourneo Custom");
ford.add("Ford Transit");
ford.add("Ford Transit Connect");
ford.add("Ford Transit Custom");
ford.add("Ford Windstar");
auto.put("Ford",ford);
System.out.println("Количество моделей Ford: "+ford.size());

ArrayList<String> honda = new ArrayList<String>();
honda.add("Honda Accord");
honda.add("Honda Avancier");
honda.add("Honda Capa");
honda.add("Honda City");
honda.add("Honda Civic");
honda.add("Honda Civic Type-R");
honda.add("Honda Concerto");
honda.add("Honda CR-V");
honda.add("Honda CR-Z");
honda.add("Honda Crosstour");
honda.add("Honda CRX");
honda.add("Honda Domani");
honda.add("Honda Element");
honda.add("Honda F-MX");
honda.add("Honda Fit");
honda.add("Honda Fit Aria");
honda.add("Honda FR-V");
honda.add("Honda Freed");
honda.add("Honda HR-V");
honda.add("Honda Insight");
honda.add("Honda Inspire");
honda.add("Honda Integra");
honda.add("Honda Jazz");
honda.add("Honda Lagreat");
honda.add("Honda Legend");
honda.add("Honda Life");
honda.add("Honda Logo");
honda.add("Honda Mobilio");
honda.add("Honda NSX");
honda.add("Honda Odyssey");
honda.add("Honda Orthia");
honda.add("Honda Partner");
honda.add("Honda Passport");
honda.add("Honda Pilot");
honda.add("Honda Prelude");
honda.add("Honda Ridgeline");
honda.add("Honda S2000");
honda.add("Honda Saber");
honda.add("Honda Shuttle");
honda.add("Honda SM-X");
honda.add("Honda Stepwgn");
honda.add("Honda Stream");
honda.add("Honda That S");
honda.add("Honda Today");
honda.add("Honda Torneo");
honda.add("Honda Vamos");
honda.add("Honda Vigor");
honda.add("Honda Z");
auto.put("Honda",honda);
System.out.println("Количество моделей Honda: "+honda.size());

ArrayList<String> hyundai = new ArrayList<String>();
hyundai.add("Hyundai Solaris седан");
hyundai.add("Hyundai Elantra седан");
hyundai.add("Hyundai Elantra седан");
hyundai.add("Hyundai Sonata седан");
hyundai.add("Hyundai i30 хэтчбек");
hyundai.add("Hyundai Palisade кроссовер");
hyundai.add("Hyundai Creta кроссовер");
hyundai.add("Hyundai Tucson кроссовер");
hyundai.add("Hyundai Tucson кроссовер");
hyundai.add("Hyundai Santa Fe Premium кроссовер");
hyundai.add("Hyundai H1 минивэн");
hyundai.add("Hyundai H1");
hyundai.add("Hyundai Accent");
hyundai.add("Hyundai Atos");
hyundai.add("Hyundai Centennial");
hyundai.add("Hyundai Coupe");
hyundai.add("Hyundai Creta");
hyundai.add("Hyundai Dynasty");
hyundai.add("Hyundai Elantra");
hyundai.add("Hyundai Equus");
hyundai.add("Hyundai Galloper");
hyundai.add("Hyundai Genesis");
hyundai.add("Hyundai Getz");
hyundai.add("Hyundai Grand Santa Fe");
hyundai.add("Hyundai Grandeur");
hyundai.add("Hyundai H100");
hyundai.add("Hyundai i20");
hyundai.add("Hyundai i30");
hyundai.add("Hyundai i40");
hyundai.add("Hyundai ix35");
hyundai.add("Hyundai ix55");
hyundai.add("Hyundai Lantra");
hyundai.add("Hyundai Lavita");
hyundai.add("Hyundai Matrix");
hyundai.add("Hyundai NF Sonata");
hyundai.add("Hyundai Pony");
hyundai.add("Hyundai Porter");
hyundai.add("Hyundai S-Coupe");
hyundai.add("Hyundai Santa Fe Classic");
hyundai.add("Hyundai Santa Fe Premium");
hyundai.add("Hyundai Santamo");
hyundai.add("Hyundai Solaris");
hyundai.add("Hyundai Sonata");
hyundai.add("Hyundai Terracan");
hyundai.add("Hyundai Trajet");
hyundai.add("Hyundai Tucson");
hyundai.add("Hyundai Veloster");
hyundai.add("Hyundai Veracruz");
hyundai.add("Hyundai Verna");
hyundai.add("Hyundai XG");
auto.put("Hyundai",hyundai);
System.out.println("Количество моделей Hyundai: "+hyundai.size());

ArrayList<String> kia = new ArrayList<String>();
kia.add("Kia K900 седан");
kia.add("Kia Cerato седан");
kia.add("Kia Rio седан");
kia.add("Kia К5 седан");
kia.add("Kia Stinger лифтбэк");
kia.add("Kia Rio хэтчбек");
kia.add("Kia Rio хэтчбек");
kia.add("Kia Stinger лифтбэк");
kia.add("Kia cee'd универсал");
kia.add("Kia cee'd хэтчбек");
kia.add("Kia cee'd универсал");
kia.add("Kia Picanto хэтчбек");
kia.add("Kia Seltos кроссовер");
kia.add("Kia Mohave внедорожник");
kia.add("Kia Soul кроссовер");
kia.add("Kia Sorento Prime кроссовер");
kia.add("Kia Sorento кроссовер");
kia.add("Kia Sportage кроссовер");
kia.add("Kia cee'd кроссовер");
kia.add("Kia Carnival минивэн");
kia.add("Kia Avella");
kia.add("Kia Besta");
kia.add("Kia Bongo");
kia.add("Kia Capital");
kia.add("Kia Carens");
kia.add("Kia Carnival");
kia.add("Kia cee'd");
kia.add("Kia cee'd GT");
kia.add("Kia Cerato");
kia.add("Kia Cerato Koup");
kia.add("Kia Clarus");
kia.add("Kia Concord");
kia.add("Kia Enterprise");
kia.add("Kia Joice");
kia.add("Kia K2700");
kia.add("Kia Magentis");
kia.add("Kia Mohave");
kia.add("Kia Opirus");
kia.add("Kia Optima");
kia.add("Kia Picanto");
kia.add("Kia Potentia");
kia.add("Kia Pregio");
kia.add("Kia Pride");
kia.add("Kia Quoris");
kia.add("Kia Retona");
kia.add("Kia Rio");
kia.add("Kia Roadster");
kia.add("Kia Sedona");
kia.add("Kia Sephia");
kia.add("Kia Shuma");
kia.add("Kia Sorento");
kia.add("Kia Sorento Prime");
kia.add("Kia Soul");
kia.add("Kia Spectra");
kia.add("Kia Sportage");
kia.add("Kia Stinger");
kia.add("Kia Venga");
kia.add("Kia Visto");
auto.put("Kia",kia);
System.out.println("Количество моделей Kia: "+kia.size());

ArrayList<String> lada = new ArrayList<String>();
lada.add("Lada (ВАЗ) Vesta седан");
lada.add("Lada (ВАЗ) Vesta Cross седан");
lada.add("Lada (ВАЗ) Vesta Sport седан");
lada.add("Lada (ВАЗ) Granta седан");
lada.add("Lada (ВАЗ) Granta Cross универсал");
lada.add("Lada (ВАЗ) Vesta SW универсал");
lada.add("Lada (ВАЗ) Vesta SW Cross универсал");
lada.add("Lada (ВАЗ) Largus универсал");
lada.add("Lada (ВАЗ) Largus Cross универсал");
lada.add("Lada (ВАЗ) Granta универсал");
lada.add("Lada (ВАЗ) Granta хэтчбек");
lada.add("Lada (ВАЗ) Granta лифтбэк");
lada.add("Lada (ВАЗ) Niva внедорожник");
lada.add("Lada (ВАЗ) XRAY кроссовер");
lada.add("Lada (ВАЗ) XRAY Cross кроссовер");
lada.add("Lada (ВАЗ) 2121 (4x4) внедорожник");
lada.add("Lada (ВАЗ) 2131 (4x4) внедорожник");
lada.add("Lada (ВАЗ) Largus фургон");
lada.add("Lada (ВАЗ) 1111 (Oka)");
lada.add("Lada (ВАЗ) 1922 (Bronto-Marsh)");
lada.add("Lada (ВАЗ) 2101");
lada.add("Lada (ВАЗ) 2102");
lada.add("Lada (ВАЗ) 2103");
lada.add("Lada (ВАЗ) 2104");
lada.add("Lada (ВАЗ) 2105");
lada.add("Lada (ВАЗ) 2106");
lada.add("Lada (ВАЗ) 2107");
lada.add("Lada (ВАЗ) 2108");
lada.add("Lada (ВАЗ) 2109");
lada.add("Lada (ВАЗ) 21099");
lada.add("Lada (ВАЗ) 2110");
lada.add("Lada (ВАЗ) 2111");
lada.add("Lada (ВАЗ) 2112");
lada.add("Lada (ВАЗ) 2113 (Samara2)");
lada.add("Lada (ВАЗ) 2114 (Samara2)");
lada.add("Lada (ВАЗ) 2115 (Samara2)");
lada.add("Lada (ВАЗ) 2120 (Nadezhda)");
lada.add("Lada (ВАЗ) 2121 (4x4)");
lada.add("Lada (ВАЗ) 2123 (4x4)");
lada.add("Lada (ВАЗ) 2131 (4x4)");
lada.add("Lada (ВАЗ) 2329 (4x4)");
lada.add("Lada (ВАЗ) 4x4 (Niva)");
lada.add("Lada (ВАЗ) 4X4 Bronto");
lada.add("Lada (ВАЗ) 4х4 Urban");
lada.add("Lada (ВАЗ) Granta");
lada.add("Lada (ВАЗ) Granta Sport");
lada.add("Lada (ВАЗ) Kalina");
lada.add("Lada (ВАЗ) Kalina Cross");
lada.add("Lada (ВАЗ) Kalina NFR");
lada.add("Lada (ВАЗ) Kalina Sport");
lada.add("Lada (ВАЗ) Largus");
lada.add("Lada (ВАЗ) Largus Cross");
lada.add("Lada (ВАЗ) Priora");
lada.add("Lada (ВАЗ) Samara II");
lada.add("Lada (ВАЗ) Vesta");
lada.add("Lada (ВАЗ) Vesta SW");
lada.add("Lada (ВАЗ) XRAY");
lada.add("Lada (ВАЗ) XRAY Cross");
auto.put("Lada (ВАЗ)",lada);
System.out.println("Количество моделей Lada (ВАЗ): "+lada.size());

ArrayList<String> mazda = new ArrayList<String>();
mazda.add("Mazda 6 седан");
mazda.add("Mazda CX-30 кроссовер");
mazda.add("Mazda CX-5 кроссовер");
mazda.add("Mazda CX-9 кроссовер");
mazda.add("Mazda CX-9 кроссовер");
mazda.add("Mazda 121");
mazda.add("Mazda 2");
mazda.add("Mazda 3");
mazda.add("Mazda 3 MPS");
mazda.add("Mazda 323");
mazda.add("Mazda 5");
mazda.add("Mazda 6");
mazda.add("Mazda 6 MPS");
mazda.add("Mazda 626");
mazda.add("Mazda 929");
mazda.add("Mazda Atenza");
mazda.add("Mazda AZ-1");
mazda.add("Mazda AZ-offroad");
mazda.add("Mazda AZ-wagon");
mazda.add("Mazda B-series");
mazda.add("Mazda Bongo");
mazda.add("Mazda BT-50");
mazda.add("Mazda Capella");
mazda.add("Mazda Carol");
mazda.add("Mazda Clef");
mazda.add("Mazda Cronos");
mazda.add("Mazda CX-3");
mazda.add("Mazda CX-5");
mazda.add("Mazda CX-7");
mazda.add("Mazda CX-9");
mazda.add("Mazda Demio");
mazda.add("Mazda E");
mazda.add("Mazda Eunos 500");
mazda.add("Mazda Eunos 800");
mazda.add("Mazda Eunos Cosmo");
mazda.add("Mazda Familia");
mazda.add("Mazda Lantis");
mazda.add("Mazda Laputa");
mazda.add("Mazda Levante");
mazda.add("Mazda Millenia");
mazda.add("Mazda MPV");
mazda.add("Mazda MX-3");
mazda.add("Mazda MX-5");
mazda.add("Mazda MX-6");
mazda.add("Mazda Navajo");
mazda.add("Mazda Premacy");
mazda.add("Mazda Revue");
mazda.add("Mazda Rustler");
mazda.add("Mazda RX-7");
mazda.add("Mazda RX-8");
mazda.add("Mazda Scrum");
mazda.add("Mazda Sentia");
mazda.add("Mazda Spiano");
mazda.add("Mazda Tribute");
mazda.add("Mazda Vantrend");
mazda.add("Mazda Xedos 6");
mazda.add("Mazda Xedos 9");
auto.put("Mazda",mazda);
System.out.println("Количество моделей Mazda: "+mazda.size());

ArrayList<String> mitsubishi = new ArrayList<String>();
mitsubishi.add("Mitsubishi Eclipse Cross кроссовер");
mitsubishi.add("Mitsubishi ASX кроссовер");
mitsubishi.add("Mitsubishi Pajero Sport внедорожник");
mitsubishi.add("Mitsubishi Pajero Sport внедорожник");
mitsubishi.add("Mitsubishi Outlander кроссовер");
mitsubishi.add("Mitsubishi L200 пикап");
mitsubishi.add("Mitsubishi 3000 GT");
mitsubishi.add("Mitsubishi Airtrek");
mitsubishi.add("Mitsubishi Aspire");
mitsubishi.add("Mitsubishi ASX");
mitsubishi.add("Mitsubishi Canter");
mitsubishi.add("Mitsubishi Carisma");
mitsubishi.add("Mitsubishi Challenger");
mitsubishi.add("Mitsubishi Chariot");
mitsubishi.add("Mitsubishi Colt");
mitsubishi.add("Mitsubishi Debonair");
mitsubishi.add("Mitsubishi Delica");
mitsubishi.add("Mitsubishi Diamante");
mitsubishi.add("Mitsubishi Dingo");
mitsubishi.add("Mitsubishi Dion");
mitsubishi.add("Mitsubishi Eclipse");
mitsubishi.add("Mitsubishi Eclipse Cross");
mitsubishi.add("Mitsubishi EK Wagon");
mitsubishi.add("Mitsubishi Emeraude");
mitsubishi.add("Mitsubishi Endeavor");
mitsubishi.add("Mitsubishi FTO");
mitsubishi.add("Mitsubishi Fuso");
mitsubishi.add("Mitsubishi Galant");
mitsubishi.add("Mitsubishi Grandis");
mitsubishi.add("Mitsubishi GTO");
mitsubishi.add("Mitsubishi i");
mitsubishi.add("Mitsubishi i-MiEV");
mitsubishi.add("Mitsubishi IO");
mitsubishi.add("Mitsubishi Jeep");
mitsubishi.add("Mitsubishi L200");
mitsubishi.add("Mitsubishi L300");
mitsubishi.add("Mitsubishi L400");
mitsubishi.add("Mitsubishi Lancer");
mitsubishi.add("Mitsubishi Lancer Classic");
mitsubishi.add("Mitsubishi Lancer Evo");
mitsubishi.add("Mitsubishi Legnum");
mitsubishi.add("Mitsubishi Libero");
mitsubishi.add("Mitsubishi Minica");
mitsubishi.add("Mitsubishi Minicab");
mitsubishi.add("Mitsubishi Mirage");
mitsubishi.add("Mitsubishi Montero");
mitsubishi.add("Mitsubishi Outlander");
mitsubishi.add("Mitsubishi Pajero");
mitsubishi.add("Mitsubishi Pajero Sport");
mitsubishi.add("Mitsubishi Pistachio");
mitsubishi.add("Mitsubishi Proudia");
mitsubishi.add("Mitsubishi RVR");
mitsubishi.add("Mitsubishi Santamo");
mitsubishi.add("Mitsubishi Sigma");
mitsubishi.add("Mitsubishi Space Gear");
mitsubishi.add("Mitsubishi Space Runner");
mitsubishi.add("Mitsubishi Space Star");
mitsubishi.add("Mitsubishi Space Wagon");
mitsubishi.add("Mitsubishi Toppo");
mitsubishi.add("Mitsubishi Town Box");
auto.put("Mitsubishi",mitsubishi);
System.out.println("Количество моделей Mitsubishi: "+mitsubishi.size());

ArrayList<String> mb = new ArrayList<String>();
mb.add("Mercedes-Benz CLA AMG седан");
mb.add("Mercedes-Benz CLS седан");
mb.add("Mercedes-Benz S седан");
mb.add("Mercedes-Benz Maybach S седан");
mb.add("Mercedes-Benz A седан");
mb.add("Mercedes-Benz C AMG купе");
mb.add("Mercedes-Benz C AMG седан");
mb.add("Mercedes-Benz C седан");
mb.add("Mercedes-Benz C купе");
mb.add("Mercedes-Benz E AMG седан");
mb.add("Mercedes-Benz E купе");
mb.add("Mercedes-Benz E седан");
mb.add("Mercedes-Benz AMG GT купе");
mb.add("Mercedes-Benz A хэтчбек");
mb.add("Mercedes-Benz E универсал");
mb.add("Mercedes-Benz AMG GT хэтчбек");
mb.add("Mercedes-Benz GLE Coupe кроссовер");
mb.add("Mercedes-Benz GLA кроссовер");
mb.add("Mercedes-Benz GLB внедорожник");
mb.add("Mercedes-Benz GLE Coupe AMG кроссовер");
mb.add("Mercedes-Benz GLS внедорожник");
mb.add("Mercedes-Benz EQC кроссовер");
mb.add("Mercedes-Benz GLE кроссовер");
mb.add("Mercedes-Benz G внедорожник");
mb.add("Mercedes-Benz G AMG внедорожник");
mb.add("Mercedes-Benz GLC кроссовер");
mb.add("Mercedes-Benz GLC AMG кроссовер");
mb.add("Mercedes-Benz GLC Coupe кроссовер");
mb.add("Mercedes-Benz GLC Coupe AMG кроссовер");
mb.add("Mercedes-Benz Sprinter микроавтобус");
mb.add("Mercedes-Benz Sprinter фургон");
mb.add("Mercedes-Benz Vito фургон");
mb.add("Mercedes-Benz Vito микроавтобус");
mb.add("Mercedes-Benz V микроавтобус");
mb.add("Mercedes-Benz 200");
mb.add("Mercedes-Benz A");
mb.add("Mercedes-Benz A AMG");
mb.add("Mercedes-Benz AMG GT");
mb.add("Mercedes-Benz B");
mb.add("Mercedes-Benz C");
mb.add("Mercedes-Benz C AMG");
mb.add("Mercedes-Benz Citan");
mb.add("Mercedes-Benz CL");
mb.add("Mercedes-Benz CL AMG");
mb.add("Mercedes-Benz CLA");
mb.add("Mercedes-Benz CLA AMG");
mb.add("Mercedes-Benz CLC");
mb.add("Mercedes-Benz CLK");
mb.add("Mercedes-Benz CLS");
mb.add("Mercedes-Benz CLS AMG");
mb.add("Mercedes-Benz E");
mb.add("Mercedes-Benz E AMG");
mb.add("Mercedes-Benz G");
mb.add("Mercedes-Benz G AMG");
mb.add("Mercedes-Benz GL");
mb.add("Mercedes-Benz GL AMG");
mb.add("Mercedes-Benz GLA");
mb.add("Mercedes-Benz GLA AMG");
mb.add("Mercedes-Benz GLC");
mb.add("Mercedes-Benz GLC AMG");
mb.add("Mercedes-Benz GLC Coupe");
mb.add("Mercedes-Benz GLC Coupe AMG");
mb.add("Mercedes-Benz GLE");
mb.add("Mercedes-Benz GLE AMG");
mb.add("Mercedes-Benz GLE Coupe");
mb.add("Mercedes-Benz GLE Coupe AMG");
mb.add("Mercedes-Benz GLK");
mb.add("Mercedes-Benz GLS");
mb.add("Mercedes-Benz GLS AMG");
mb.add("Mercedes-Benz M");
mb.add("Mercedes-Benz M AMG");
mb.add("Mercedes-Benz Maybach S");
mb.add("Mercedes-Benz R");
mb.add("Mercedes-Benz R AMG");
mb.add("Mercedes-Benz S");
mb.add("Mercedes-Benz S AMG");
mb.add("Mercedes-Benz SL");
mb.add("Mercedes-Benz SL AMG");
mb.add("Mercedes-Benz SLC");
mb.add("Mercedes-Benz SLC AMG");
mb.add("Mercedes-Benz SLK");
mb.add("Mercedes-Benz SLK AMG");
mb.add("Mercedes-Benz SLR");
mb.add("Mercedes-Benz SLS AMG");
mb.add("Mercedes-Benz Sprinter");
mb.add("Mercedes-Benz V");
mb.add("Mercedes-Benz Vaneo");
mb.add("Mercedes-Benz Vario");
mb.add("Mercedes-Benz Viano");
mb.add("Mercedes-Benz Vito");
mb.add("Mercedes-Benz W100");
mb.add("Mercedes-Benz X-class");
auto.put("Mercedes-Benz",mb);
System.out.println("Количество моделей Mercedes-Benz: "+mb.size());

ArrayList<String> nissan = new ArrayList<String>();
nissan.add("Nissan Ariya кроссовер");
nissan.add("Nissan Qashqai кроссовер");
nissan.add("Nissan Murano кроссовер");
nissan.add("Nissan Terrano кроссовер");
nissan.add("Nissan X-Trail кроссовер");
nissan.add("Nissan 200 SX");
nissan.add("Nissan 300 ZX");
nissan.add("Nissan 350 Z");
nissan.add("Nissan AD");
nissan.add("Nissan Almera");
nissan.add("Nissan Almera Classic");
nissan.add("Nissan Almera Tino");
nissan.add("Nissan Altima");
nissan.add("Nissan Armada");
nissan.add("Nissan Atleon");
nissan.add("Nissan Avenir");
nissan.add("Nissan Bassara");
nissan.add("Nissan Bluebird");
nissan.add("Nissan Cabstar");
nissan.add("Nissan Cedric");
nissan.add("Nissan Cefiro");
nissan.add("Nissan Cima");
nissan.add("Nissan Crew");
nissan.add("Nissan Cube");
nissan.add("Nissan Datsun");
nissan.add("Nissan Elgrand");
nissan.add("Nissan Gloria");
nissan.add("Nissan GT-R");
nissan.add("Nissan Juke");
nissan.add("Nissan Lafesta");
nissan.add("Nissan Largo");
nissan.add("Nissan Laurel");
nissan.add("Nissan Leaf");
nissan.add("Nissan Liberty");
nissan.add("Nissan Lucino");
nissan.add("Nissan March");
nissan.add("Nissan Maxima");
nissan.add("Nissan Micra");
nissan.add("Nissan Moco");
nissan.add("Nissan Murano");
nissan.add("Nissan Navara");
nissan.add("Nissan Note");
nissan.add("Nissan NP300");
nissan.add("Nissan Pathfinder");
nissan.add("Nissan Patrol");
nissan.add("Nissan Pick-up");
nissan.add("Nissan Pixo");
nissan.add("Nissan Prairie");
nissan.add("Nissan Presage");
nissan.add("Nissan Presea");
nissan.add("Nissan President");
nissan.add("Nissan Primastar");
nissan.add("Nissan Primera");
nissan.add("Nissan Pulsar");
nissan.add("Nissan Qashqai");
nissan.add("Nissan Qashqai+2");
nissan.add("Nissan Quest");
nissan.add("Nissan R Nessa");
nissan.add("Nissan Rasheen");
nissan.add("Nissan Rouge");
nissan.add("Nissan Safari");
nissan.add("Nissan Sentra");
nissan.add("Nissan Serena");
nissan.add("Nissan Silvia");
nissan.add("Nissan Skyline");
nissan.add("Nissan Stagea");
nissan.add("Nissan Sunny");
nissan.add("Nissan Teana");
nissan.add("Nissan Terrano");
nissan.add("Nissan Tiida");
nissan.add("Nissan Tino");
nissan.add("Nissan Urvan");
nissan.add("Nissan Vanette");
nissan.add("Nissan Wingroad");
nissan.add("Nissan X-Terra");
nissan.add("Nissan X-Trail");
auto.put("Nissan",nissan);
System.out.println("Количество моделей Nissan: "+nissan.size());

ArrayList<String> renault = new ArrayList<String>();
renault.add("Renault Logan Stepway седан");
renault.add("Renault Logan седан");
renault.add("Хэтчбеки, лифтбеки, универсалы");
renault.add("Renault Sandero хэтчбек");
renault.add("Renault Arkana кроссовер");
renault.add("Renault Kaptur кроссовер");
renault.add("Renault Duster кроссовер");
renault.add("Renault Duster кроссовер");
renault.add("Renault Sandero Stepway кроссовер");
renault.add("Renault Master фургон");
renault.add("Renault 19");
renault.add("Renault Avantime");
renault.add("Renault Clio");
renault.add("Renault Clio RS");
renault.add("Renault Dokker");
renault.add("Renault Dokker Stepway");
renault.add("Renault Duster");
renault.add("Renault Espace");
renault.add("Renault Fluence");
renault.add("Renault Grand Scenic");
renault.add("Renault Kangoo");
renault.add("Renault Kangoo Z.E.");
renault.add("Renault Kaptur");
renault.add("Renault Koleos");
renault.add("Renault Laguna");
renault.add("Renault Latitude");
renault.add("Renault Logan");
renault.add("Renault Master");
renault.add("Renault Megane");
renault.add("Renault Megane RS");
renault.add("Renault Modus");
renault.add("Renault Safrane");
renault.add("Renault Sandero");
renault.add("Renault Sandero Stepway");
renault.add("Renault Scenic");
renault.add("Renault Sport Spider");
renault.add("Renault Symbol");
renault.add("Renault Trafic");
renault.add("Renault Twingo");
renault.add("Renault TWIZY");
renault.add("Renault Vel Satis");
auto.put("Renault",renault);
System.out.println("Количество моделей Renault: "+renault.size());

ArrayList<String> skoda = new ArrayList<String>();
skoda.add("Skoda Rapid лифтбэк");
skoda.add("Skoda Superb лифтбэк");
skoda.add("Skoda Superb универсал");
skoda.add("Skoda Octavia универсал");
skoda.add("Skoda Octavia лифтбэк");
skoda.add("Skoda Karoq кроссовер");
skoda.add("Skoda Kodiaq кроссовер");
skoda.add("Skoda Fabia");
skoda.add("Skoda Fabia RS");
skoda.add("Skoda Fabia Scout");
skoda.add("Skoda Favorit");
skoda.add("Skoda Felicia");
skoda.add("Skoda Kamiq");
skoda.add("Skoda Octavia");
skoda.add("Skoda Octavia RS");
skoda.add("Skoda Octavia Scout");
skoda.add("Skoda Octavia Tour");
skoda.add("Skoda Praktik");
skoda.add("Skoda Rapid");
skoda.add("Skoda Roomster");
skoda.add("Skoda Roomster Scout");
skoda.add("Skoda Scala");
skoda.add("Skoda Superb");
skoda.add("Skoda Yeti");
auto.put("Skoda",skoda);
System.out.println("Количество моделей Skoda: "+skoda.size());

ArrayList<String> toyota = new ArrayList<String>();
toyota.add("Toyota Supra купе");
toyota.add("Toyota Camry седан");
toyota.add("Toyota Corolla седан");
toyota.add("Toyota Land Cruiser Prado внедорожник");
toyota.add("Toyota Land Cruiser внедорожник");
toyota.add("Toyota C-HR кроссовер");
toyota.add("Toyota Fortuner внедорожник");
toyota.add("Toyota Highlander кроссовер");
toyota.add("Toyota RAV4 кроссовер");
toyota.add("Toyota Alphard минивэн");
toyota.add("Toyota Hilux пикап");
toyota.add("Toyota Hiace микроавтобус");
toyota.add("Toyota 4runner");
toyota.add("Toyota Allex");
toyota.add("Toyota Allion");
toyota.add("Toyota Alphard");
toyota.add("Toyota Altezza");
toyota.add("Toyota Aristo");
toyota.add("Toyota Aurion");
toyota.add("Toyota Auris");
toyota.add("Toyota Avalon");
toyota.add("Toyota Avensis");
toyota.add("Toyota Aygo");
toyota.add("Toyota BB");
toyota.add("Toyota Belta");
toyota.add("Toyota Blade");
toyota.add("Toyota Blizzard");
toyota.add("Toyota Brevis");
toyota.add("Toyota C-HR");
toyota.add("Toyota Caldina");
toyota.add("Toyota Cami");
toyota.add("Toyota Camry");
toyota.add("Toyota Carina");
toyota.add("Toyota Cavalier");
toyota.add("Toyota Celica");
toyota.add("Toyota Celsior");
toyota.add("Toyota Century");
toyota.add("Toyota Chaser");
toyota.add("Toyota Corolla");
toyota.add("Toyota Corolla Ceres");
toyota.add("Toyota Corolla Levin");
toyota.add("Toyota Corolla Rumion");
toyota.add("Toyota Corolla Spacio");
toyota.add("Toyota Corolla Verso");
toyota.add("Toyota Corona");
toyota.add("Toyota Corsa");
toyota.add("Toyota Cressida");
toyota.add("Toyota Cresta");
toyota.add("Toyota Crown");
toyota.add("Toyota Curren");
toyota.add("Toyota Cynos");
toyota.add("Toyota Duet");
toyota.add("Toyota Dyna");
toyota.add("Toyota Echo");
toyota.add("Toyota Estima");
toyota.add("Toyota Estima Lucida");
toyota.add("Toyota FJ Cruiser");
toyota.add("Toyota Fortuner");
toyota.add("Toyota Funcargo");
toyota.add("Toyota Gaia");
toyota.add("Toyota Grand Hiace");
toyota.add("Toyota Granvia");
toyota.add("Toyota GT86");
toyota.add("Toyota Harrier");
toyota.add("Toyota Hiace");
toyota.add("Toyota Highlander");
toyota.add("Toyota Hilux");
toyota.add("Toyota Hilux Surf");
toyota.add("Toyota Innova");
toyota.add("Toyota Ipsum");
toyota.add("Toyota iQ");
toyota.add("Toyota Isis");
toyota.add("Toyota Ist");
toyota.add("Toyota Kluger Hybrid");
toyota.add("Toyota Kluger V");
toyota.add("Toyota Land Cruiser");
toyota.add("Toyota Land Cruiser Prado");
toyota.add("Toyota Liteace");
toyota.add("Toyota Mark");
toyota.add("Toyota Mark X");
toyota.add("Toyota Matrix");
toyota.add("Toyota Mega Cruiser");
toyota.add("Toyota MR 2");
toyota.add("Toyota Nadia");
toyota.add("Toyota Noah");
toyota.add("Toyota Opa");
toyota.add("Toyota Paseo");
toyota.add("Toyota Passo");
toyota.add("Toyota Picnic");
toyota.add("Toyota Platz");
toyota.add("Toyota Premio");
toyota.add("Toyota Previa");
toyota.add("Toyota Prius");
toyota.add("Toyota Probox");
toyota.add("Toyota Progres");
toyota.add("Toyota Pronard");
toyota.add("Toyota Ractis");
toyota.add("Toyota Raum");
toyota.add("Toyota RAV4");
toyota.add("Toyota Regius");
toyota.add("Toyota Rush");
toyota.add("Toyota Sai");
toyota.add("Toyota Scepter");
toyota.add("Toyota Sequoia");
toyota.add("Toyota Sera");
toyota.add("Toyota Sienna");
toyota.add("Toyota Sienta");
toyota.add("Toyota Soarer");
toyota.add("Toyota Solara");
toyota.add("Toyota Sparky");
toyota.add("Toyota Sprinter");
toyota.add("Toyota Starlet");
toyota.add("Toyota Succeed");
toyota.add("Toyota Supra");
toyota.add("Toyota Tacoma");
toyota.add("Toyota Tercel");
toyota.add("Toyota Town Ace Noah");
toyota.add("Toyota Tundra");
toyota.add("Toyota Urban Cruiser");
toyota.add("Toyota Vanguard");
toyota.add("Toyota Vellfire");
toyota.add("Toyota Venza");
toyota.add("Toyota Verossa");
toyota.add("Toyota Verso");
toyota.add("Toyota Vista");
toyota.add("Toyota Vitz");
toyota.add("Toyota Voltz");
toyota.add("Toyota Voxy");
toyota.add("Toyota Will Cypha");
toyota.add("Toyota Will Vi");
toyota.add("Toyota Will Vs");
toyota.add("Toyota Windom");
toyota.add("Toyota Wish");
toyota.add("Toyota Yaris");
auto.put("Toyota",toyota);
System.out.println("Количество моделей Toyota: "+toyota.size());

ArrayList<String> volkswagen = new ArrayList<String>();
volkswagen.add("Volkswagen Polo седан");
volkswagen.add("Volkswagen Jetta седан");
volkswagen.add("Volkswagen Passat седан");
volkswagen.add("Volkswagen Golf хэтчбек");
volkswagen.add("Volkswagen Teramont кроссовер");
volkswagen.add("Volkswagen Tiguan кроссовер");
volkswagen.add("Volkswagen Tiguan кроссовер");
volkswagen.add("Volkswagen Touareg внедорожник");
volkswagen.add("Volkswagen Transporter минивэн");
volkswagen.add("Volkswagen Crafter грузовик");
volkswagen.add("Volkswagen Crafter фургон");
volkswagen.add("Volkswagen California микроавтобус");
volkswagen.add("Volkswagen Transporter фургон");
volkswagen.add("Volkswagen Transporter бортовой грузовик");
volkswagen.add("Volkswagen Caravelle микроавтобус");
volkswagen.add("Volkswagen Multivan микроавтобус");
volkswagen.add("Volkswagen Amarok");
volkswagen.add("Volkswagen Arteon");
volkswagen.add("Volkswagen Beetle");
volkswagen.add("Volkswagen Bora");
volkswagen.add("Volkswagen Caddy");
volkswagen.add("Volkswagen California");
volkswagen.add("Volkswagen Caravelle");
volkswagen.add("Volkswagen Corrado");
volkswagen.add("Volkswagen Crafter");
volkswagen.add("Volkswagen Cross Touran");
volkswagen.add("Volkswagen CrossGolf");
volkswagen.add("Volkswagen CrossPolo");
volkswagen.add("Volkswagen Eos");
volkswagen.add("Volkswagen Fox");
volkswagen.add("Volkswagen Golf");
volkswagen.add("Volkswagen Golf GTE");
volkswagen.add("Volkswagen Golf GTI");
volkswagen.add("Volkswagen Golf Plus");
volkswagen.add("Volkswagen Golf R");
volkswagen.add("Volkswagen Jetta");
volkswagen.add("Volkswagen Lupo");
volkswagen.add("Volkswagen Multivan");
volkswagen.add("Volkswagen Passat");
volkswagen.add("Volkswagen Passat Alltrack");
volkswagen.add("Volkswagen Passat CC");
volkswagen.add("Volkswagen Phaeton");
volkswagen.add("Volkswagen Pointer");
volkswagen.add("Volkswagen Polo");
volkswagen.add("Volkswagen Polo GTI");
volkswagen.add("Volkswagen Routan");
volkswagen.add("Volkswagen Scirocco");
volkswagen.add("Volkswagen Sharan");
volkswagen.add("Volkswagen Teramont");
volkswagen.add("Volkswagen Tiguan");
volkswagen.add("Volkswagen Touareg");
volkswagen.add("Volkswagen Touran");
volkswagen.add("Volkswagen Transporter");
volkswagen.add("Volkswagen Vento");
volkswagen.add("Volkswagen W12");
auto.put("Volkswagen",volkswagen);
System.out.println("Количество моделей Volkswagen: "+volkswagen.size());

ArrayList<String> acura = new ArrayList<String>();
acura.add("Acura CL");
acura.add("Acura EL");
acura.add("Acura ILX");
acura.add("Acura Integra");
acura.add("Acura MDX");
acura.add("Acura NSX");
acura.add("Acura RDX");
acura.add("Acura RL");
acura.add("Acura RSX");
acura.add("Acura SLX");
acura.add("Acura TL");
acura.add("Acura TLX");
acura.add("Acura TSX");
auto.put("Acura",acura);
System.out.println("Количество моделей Acura: "+acura.size());

ArrayList<String> daihatsu = new ArrayList<String>();
daihatsu.add("Daihatsu Altis");
daihatsu.add("Daihatsu Applause");
daihatsu.add("Daihatsu Atrai");
daihatsu.add("Daihatsu Boon");
daihatsu.add("Daihatsu Charade");
daihatsu.add("Daihatsu Copen");
daihatsu.add("Daihatsu Cuore");
daihatsu.add("Daihatsu Delta");
daihatsu.add("Daihatsu Esse");
daihatsu.add("Daihatsu Extol");
daihatsu.add("Daihatsu Feroza");
daihatsu.add("Daihatsu Materia");
daihatsu.add("Daihatsu MAX");
daihatsu.add("Daihatsu Mira");
daihatsu.add("Daihatsu Move");
daihatsu.add("Daihatsu Naked");
daihatsu.add("Daihatsu Rocky");
daihatsu.add("Daihatsu Rugger");
daihatsu.add("Daihatsu Sirion");
daihatsu.add("Daihatsu Terios");
daihatsu.add("Daihatsu YRV");
auto.put("Daihatsu",daihatsu);
System.out.println("Количество моделей Daihatsu: "+daihatsu.size());

ArrayList<String> datsun = new ArrayList<String>();
datsun.add("Datsun on-DO седан");
datsun.add("Datsun mi-DO хэтчбек");
auto.put("Datsun",datsun);
System.out.println("Количество моделей Datsun: "+datsun.size());

ArrayList<String> infiniti = new ArrayList<String>();
infiniti.add("Infiniti Q50 седан");
infiniti.add("Infiniti Q60 купе");
infiniti.add("Infiniti QX60 кроссовер");
infiniti.add("Infiniti QX50 кроссовер");
infiniti.add("Infiniti QX80 внедорожник");
infiniti.add("Infiniti EX");
infiniti.add("Infiniti FX");
infiniti.add("Infiniti G");
infiniti.add("Infiniti G20");
infiniti.add("Infiniti I30");
infiniti.add("Infiniti I35");
infiniti.add("Infiniti J30");
infiniti.add("Infiniti JX");
infiniti.add("Infiniti M");
infiniti.add("Infiniti M35");
infiniti.add("Infiniti M45");
infiniti.add("Infiniti Q30");
infiniti.add("Infiniti Q40");
infiniti.add("Infiniti Q45");
infiniti.add("Infiniti Q50");
infiniti.add("Infiniti Q60");
infiniti.add("Infiniti Q70");
infiniti.add("Infiniti QX");
infiniti.add("Infiniti QX30");
infiniti.add("Infiniti QX4");
infiniti.add("Infiniti QX50");
infiniti.add("Infiniti QX60");
infiniti.add("Infiniti QX70");
infiniti.add("Infiniti QX80");
auto.put("Infiniti",infiniti);
System.out.println("Количество моделей Infiniti: "+infiniti.size());

ArrayList<String> isuzu = new ArrayList<String>();
isuzu.add("Isuzu D-Max пикап");
isuzu.add("Isuzu D-Max пикап");
isuzu.add("Isuzu Ascender");
isuzu.add("Isuzu Aska");
isuzu.add("Isuzu Axiom");
isuzu.add("Isuzu D-Max");
isuzu.add("Isuzu Impulse");
isuzu.add("Isuzu Rodeo");
isuzu.add("Isuzu Trooper");
isuzu.add("Isuzu VehiCross");
auto.put("Isuzu",isuzu);
System.out.println("Количество моделей Isuzu: "+isuzu.size());

return auto;
    }
}
